#!/bin/sh
#
# USE AT YOUR OWN RISK
#
# This script creates a direcotry and Pkgfile in directory with
# all necessary header information fields and an empty build() function.

if [ -z "$1" ]; then
    echo "Port directory is empty!"
    exit 1
fi

if [ -f "$1/Pkgfile" ]; then
    echo "Port exists!"
    exit 1
fi

name="$(basename $1)"
mkdir -p "$1"

cat <<EOF > $1/Pkgfile
# Description:
# URL:
# Maintainer:
# Depends on:

name=$name
version=
release=1
source=()

build() {
	cd \$name-\$version
}
EOF

echo "$name" >> "${1%$name}list"
echo "Port '$name' successfully created."

exit 0
