#!/bin/sh

if [ -f /etc/sgml/sgml-ent.cat ]; then
    install-catalog --remove /etc/sgml/sgml-ent.cat \
		/usr/share/sgml/sgml-iso-entities-8879.1986/catalog &>/dev/null
fi

if [ -f /etc/sgml/sgml-docbook.cat ]; then
	install-catalog --remove /etc/sgml/sgml-docbook.cat \
		/etc/sgml/sgml-ent.cat &>/dev/null
fi